### ISSUE TITLE
Failed to build module 'Fastboard' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug

### ISSUE THREAD

**Issue by manikandan-artium** [netless-io/Fastboard-iOS#2]
using Fastboard framework inside my swift library packages I am facing this issue.
@vince-hz @0xvince01 can you help me on this?

**Comment by vince-hz** [comment]
Sure. You mean you are using Fastboard framework in your swift library packages.
This is a rare use, can you provide the sample project code please?
Also what version of the XCode are you using, that ,might help!

You can send example code to this email: xuyunshi@agora.io
@manikandan-artium

**Comment by manikandan-artium** [comment]
@vince-hz I have pushed my sample project to this https://github.com/manikandan-artium/FastboardSample repo.

**Comment by vince-hz** [comment]
OK, I see you want to use swift package manager.
I will help you to do so. Just give me a little time.
@manikandan-artium

**Comment by manikandan-artium** [comment]
Thanks for the quick response. It will be beneficial if I get the solution very soon.

**Comment by vince-hz** [comment]
Hi, I had create a branch to adapt swift package manager already.
You can try this way to integerate Fastboard into your project now.

```
.package(url: "https://github.com/netless-io/fastboard-iOS", branch: "SPM")
```

Just leave your message here if you had any further questions.
@manikandan-artium

**Comment by vince-hz** [comment]
This approach had no release tag yet.
By the way, this version need XCode 15.0 and upper. Because there were some problem about mixing Objective-C and Swift when I use swift-tools-version lower than 5.9.

**Comment by manikandan-artium** [comment]
Thanks for the solution, Let me try and I will share the response soon

**Comment by manikandan-artium** [comment]
@vince-hz Thanks for solution now Fastboard working properly with our app.
