### ISSUE TITLE
Zoom Fastboard

### ISSUE THREAD

**Issue by sheetal2795** [netless-io/Fastboard-iOS#4]
When 2 users join a room and one of them zooms it, the same view (zoomed view) is visible to the other user.
Can I disable this?

**Comment by vince-hz** [comment]
This involves the issue of user 's view mode. It's hard to keep this behavior always right. As for fastboard, we always keep all users in the room saw the same view. You can try `WhiteViewMode` in the `Whiteboard` library if you want to control the user's viewmode.

Here is a document can help you know what is all about view mode. https://developer.netless.link/ios-zh/home/ios-view
