### ISSUE TITLE
Fastboard youtube Player not play the video which is share by the user

### ISSUE THREAD

**Issue by manikandan-artium** [netless-io/Fastboard-iOS#5]
@vince-hz @0xvince01 We are using Fastboard in our app, earlier the YouTube video played, and now some videos from YouTube are not playing properly.

**Comment by vince-hz** [comment]
Can you provide the link to the video that won't play and describe the error you're experiencing? @manikandan-artium

**Comment by manikandan-artium** [comment]
@vince-hz I here attached the video link and error details for your reference

https://youtu.be/Ju6kNKaBOQ8?si=jpDdyMU_0lKD4jKQ
https://youtu.be/CNZMIhckaA0?si=28_U5LsWcL9_1PaA
https://youtu.be/hZuwe72Rtcc?si=KweE4O8qJEHyJlMs
https://youtu.be/zLGZhp14UgY?si=gDq5OcmTvBSbtncV
https://youtu.be/ag3ENMEV89o?si=hqgagtnZn6coN9RG

![image](https://github.com/netless-io/fastboard-iOS/assets/104821071/73d8c49b-d506-4494-9581-fb883a7d3717)

**Comment by vince-hz** [comment]
> @vince-hz I here attached the video link and error details for your reference
> 
> https://youtu.be/Ju6kNKaBOQ8?si=jpDdyMU_0lKD4jKQ https://youtu.be/CNZMIhckaA0?si=28_U5LsWcL9_1PaA https://youtu.be/hZuwe72Rtcc?si=KweE4O8qJEHyJlMs https://youtu.be/zLGZhp14UgY?si=gDq5OcmTvBSbtncV https://youtu.be/ag3ENMEV89o?si=hqgagtnZn6coN9RG
> 
> ![image](https://private-user-images.githubusercontent.com/104821071/288353336-73d8c49b-d506-4494-9581-fb883a7d3717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTQzNzUsIm5iZiI6MTcwMTg1NDA3NSwicGF0aCI6Ii8xMDQ4MjEwNzEvMjg4MzUzMzM2LTczZDhjNDliLWQ1MDYtNDQ5NC05NTgxLWZiODgzYTdkMzcxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwOTE0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjM2ZWZhMGIxNjMxMDk2MTQxMWY0ODBjZjcxNzIyMzlkMDNiNDg3YzI3NWJhMWFjMjg2ODVlZTNkNTk0ZmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XbApowGhYrvIEqXfCe9-0jhPZBoq2gCUZfkh8JH9otY)

These videos do not support embedded playback. This is a limitation imposed by the author. You can confirm it by clicking on 'Share' - 'Embbed'。
<img width="1531" alt="image" src="https://github.com/netless-io/fastboard-iOS/assets/26054167/d35372a3-1e4a-4de2-9af5-138e8c50ef99">

**Comment by manikandan-artium** [comment]
@vince-hz check with other videos,
https://www.youtube.com/watch?v=h1BGDHumhj4
https://youtu.be/CNZMIhckaA0?si=28_U5LsWcL9_1PaA
https://youtu.be/hZuwe72Rtcc?si=KweE4O8qJEHyJlMs
https://youtu.be/zLGZhp14UgY?si=gDq5OcmTvBSbtncV
https://youtu.be/ag3ENMEV89o?si=hqgagtnZn6coN9RG

these video support embedded option

**Comment by vince-hz** [comment]
@manikandan-artium 
These video don't support embbed either. You can just copy the code in the share box or the embbed video link to confirm that the link he provided is not working.

<img width="1597" alt="image" src="https://github.com/netless-io/fastboard-iOS/assets/26054167/20991244-4fd9-48ff-8ecb-ee001046438f">
