### ISSUE TITLE
YY model is removed

### ISSUE THREAD

**Issue by MaheshGC98** [netless-io/Fastboard-iOS#6]
@vince-hz  @0xvince01  we are using SPM branch in our project. which have dependency of YY model now which is updated to different repo so please do the needful and update the SPM branch with master.

**Comment by vince-hz** [comment]
@MaheshGC98 We had update support for SPM. Try the latest version '1.4.0' on master please.

**Comment by MaheshGC98** [comment]
> y the latest version '1.4.

this worked. Thank you
